"""
Vectorized preprocessing pipeline — handles 10,000+ rows efficiently.

Strategy:
  1. Load all_reviews.csv (generated by data_generator) or legacy JSON files.
  2. If neither exists, auto-generate the synthetic baseline via data_generator.
  3. Noise filtering and discovery signal detection via pandas str.contains()
     (compiled regex, no Python-level loops over rows).
  4. Enrichment (root causes, segment, frustrations) applied per-row via apply()
     only on the ~6,500 rows that passed noise filtering.
  5. Persist to data/processed/ as JSON + stats.
"""
from __future__ import annotations

import json
import logging
import re
from collections import Counter
from pathlib import Path

import pandas as pd

logger = logging.getLogger(__name__)

# ── Compiled pattern sets (vectorized use) ─────────────────────────────────

# At least one match → keep as signal
_SIGNAL_PATTERNS = (
    r"discover weekly|echo chamber|same song|recommendation loop"
    r"|stale music|autoplay repeat|radio repeat|feedback loop"
    r"|recommendation.*boring|boring.*recommendation|stuck in.*loop"
    r"|same.*playlist|repetitive.*algorithm|algorithm.*repetitive"
    r"|discovery.*broken|broken.*discovery|recommendation.*stale"
    r"|always.*same|keeps? playing|music.*loop|loop.*music"
    r"|daily mix.*same|same.*daily mix|genre.*bubble|taste.*bubble"
    r"|algorithm.*bad|bad.*algorithm|radio.*same|same.*radio"
    r"|never.*new|autoplay.*same|same.*autoplay|filter.*bubble"
    r"|profile.*locked|locked.*genre|algorithmic.*fatigue"
    r"|taste profile|discovery.*fail|echo.*algorithm|algorithm.*echo"
    r"|discover.*weekly.*useless|discover.*weekly.*broken|stale.*recommend"
)

# Any match → classify as noise (exclude)
_NOISE_PATTERNS = (
    r"login.*issue|can'?t.*login|can'?t.*log in|password.*reset|account.*locked"
    r"|payment.*fail|charge.*wrong|billing.*error|refund"
    r"|app.*crash|crash.*app|app.*not.*open|won'?t.*open|keeps? crashing"
    r"|loading.*issue|buffering.*slow|download.*fail|won'?t.*download"
    r"|bluetooth.*disconnect|headphone.*glitch|audio.*delay"
    r"|sync.*problem|offline.*mode.*broken|storage.*full"
    r"|update.*broke|after.*update.*problem|cancel.*subscription"
    r"|how.*cancel|delete.*account|forgot.*password"
    r"|student.*discount.*not.*working|family.*plan.*billing"
    r"|crossfade.*not.*working|equalizer.*bug|lyrics.*not.*show"
    r"|share.*playlist.*not|podcast.*download.*fail|two-factor"
    r"|two factor|2fa|error code|error 40[0-9]|memory leak"
)

_NOISE_RE = re.compile(_NOISE_PATTERNS, re.IGNORECASE)
_SIGNAL_RE = re.compile(_SIGNAL_PATTERNS, re.IGNORECASE)

# Per-tag regex patterns (for enrichment apply())
ROOT_CAUSE_RULES = {
    "Feedback Loop Bias": re.compile(
        r"same song|loop|repeat|cycle|feedback|reinforc|always.*same|keeps? playing", re.I),
    "Passive Fatigue": re.compile(
        r"passive.*listen|background.*music|work.*listen|sleep.*playlist"
        r"|algorithmically.*tired|fatigue|no longer excited|stopped.*enjoy", re.I),
    "Contextual Over-reliance": re.compile(
        r"gym.*playlist|workout.*bleed|context.*aware|different.*context"
        r"|mood.*mismatch|commute.*music|sleep.*contaminate", re.I),
    "Genre Bubble": re.compile(
        r"echo chamber|genre.*bubble|filter.*bubble|locked.*genre"
        r"|stuck.*genre|can'?t.*escape.*genre", re.I),
    "Taste Evolution Lag": re.compile(
        r"taste.*changed|different.*now|moved on|used to.*like"
        r"|evolved.*taste|new.*phase|algorithm.*won'?t.*update|old.*recommend", re.I),
    "Niche Content Gap": re.compile(
        r"niche.*genre|underground|obscure|long.*tail|too.*mainstream|indie.*ignored", re.I),
    "Cold Start Anchoring": re.compile(
        r"first.*week|onboarding|new.*user|just.*started|initial.*listen"
        r"|first.*few.*days|locked.*after.*week", re.I),
}

FRUSTRATION_PATTERNS = {
    "Discover Weekly Quality": re.compile(
        r"discover weekly|dw\b|discover.*stale|discover.*weekly.*bad", re.I),
    "Radio Repetition": re.compile(
        r"radio.*same|radio.*loop|radio.*repeat|artist.*radio.*loop|radio.*30.*song", re.I),
    "Autoplay Loop": re.compile(
        r"autoplay.*same|autoplay.*repeat|after.*playlist.*same", re.I),
    "Daily Mix Stagnation": re.compile(
        r"daily mix.*same|daily mix.*boring|daily mix.*repeat", re.I),
    "No Escape Mechanism": re.compile(
        r"can'?t.*escape|no.*way.*reset|reset.*option|stuck", re.I),
    "Cross-Context Contamination": re.compile(
        r"gym.*contaminate|podcast.*music.*mix|cross.*contaminate|work.*playlist.*bleed", re.I),
    "Algorithm Transparency": re.compile(
        r"don'?t.*understand.*algorithm|algorithm.*mystery|why.*recommend", re.I),
}

SEGMENT_PATTERNS = {
    "Power Curator": re.compile(
        r"playlist.*curate|\d+.*playlist|curated.*playlist|hours.*playlist"
        r"|carefully.*select|organize.*music", re.I),
    "Passive Radio Listener": re.compile(
        r"background.*music|passive.*listen|put.*on.*kitchen"
        r"|work.*from.*home.*music|always.*on.*radio|just.*plays|let.*it.*play", re.I),
    "Genre Explorer": re.compile(
        r"explore.*genre|try.*different|branch.*out|eclectic.*taste"
        r"|wide.*range|multiple.*genre|genre.*hopping|curiosity", re.I),
    "Loyal Long-Timer": re.compile(
        r"\d+.*year.*spotify|been.*using.*\d+.*year|long.*time.*user"
        r"|since.*201[0-9]|since.*launch|remember.*when|used.*to.*be.*better", re.I),
    "Free Tier Casual": re.compile(
        r"free.*tier|free.*user|not.*premium|free.*version|free.*plan"
        r"|don'?t.*pay|free account", re.I),
}

PREMIUM_SIGNALS = re.compile(
    r"\bpremium\b|premium.*user|paying.*for.*spotify|£\d+|\$\d+.*month"
    r"|per month|subscription.*fee|family.*plan|student.*plan"
    r"|annual.*plan|upgrade.*to.*premium", re.I)

FREE_SIGNALS = re.compile(
    r"\bfree\b.*\btier\b|\bfree\b.*\buser\b|\bfree\b.*\bplan\b|\bfree\b.*\bversion\b"
    r"|not.*premium|without.*premium|free.*account|ads.*during|interrupted.*by.*ads", re.I)


# ── Loading ────────────────────────────────────────────────────────────────

def _get_data_dir() -> Path:
    return Path(__file__).parent.parent.parent / "data"


def load_csv_raw(csv_path: Path) -> pd.DataFrame:
    df = pd.read_csv(csv_path, dtype=str, low_memory=False)
    df["text"] = (
        df.get("title", pd.Series(dtype=str)).fillna("") + " "
        + df.get("body", pd.Series(dtype=str)).fillna("")
    ).str.strip()
    df["sentiment_raw"] = pd.to_numeric(df.get("sentiment_raw", pd.Series(dtype=float)), errors="coerce").fillna(0.0)
    return df


def load_json_raw(data_dir: Path) -> pd.DataFrame:
    """Fallback: load all JSON files from data/raw/."""
    records = []
    for f in (data_dir / "raw").glob("*.json"):
        try:
            with open(f, encoding="utf-8") as fh:
                data = json.load(fh)
            if isinstance(data, list):
                records.extend(data)
            elif isinstance(data, dict):
                records.append(data)
        except Exception as e:
            logger.warning("Could not load %s: %s", f.name, e)

    df = pd.DataFrame(records)
    if "body" not in df.columns and "comment" in df.columns:
        df["body"] = df["comment"]
    df["text"] = (
        df.get("title", pd.Series(dtype=str)).fillna("") + " "
        + df.get("body", pd.Series(dtype=str)).fillna("")
    ).str.strip()
    if "sentiment_raw" not in df.columns:
        df["sentiment_raw"] = 0.0
    df["sentiment_raw"] = pd.to_numeric(df["sentiment_raw"], errors="coerce").fillna(0.0)
    return df


def load_or_generate(data_dir: Path | None = None) -> pd.DataFrame:
    """
    Precedence:
      1. data/raw/all_reviews.csv  (large synthetic or real dataset)
      2. Legacy JSON files in data/raw/
      3. Auto-generate 8,500-row synthetic baseline and return it
    """
    if data_dir is None:
        data_dir = _get_data_dir()

    csv_path = data_dir / "raw" / "all_reviews.csv"
    if csv_path.exists():
        logger.info("Loading CSV dataset from %s", csv_path)
        df = load_csv_raw(csv_path)
        logger.info("Loaded %d rows from CSV", len(df))
        return df

    json_files = list((data_dir / "raw").glob("*.json"))
    if json_files:
        logger.info("Loading %d JSON files from %s/raw/", len(json_files), data_dir)
        df = load_json_raw(data_dir)
        logger.info("Loaded %d rows from JSON files", len(df))
        return df

    # Auto-generate
    logger.warning("No raw data found — generating 8,500-row synthetic baseline")
    try:
        from src.data_generator import generate_dataset
        generated_path = generate_dataset(output_path=csv_path)
        df = load_csv_raw(generated_path)
        logger.info("Generated and loaded %d synthetic rows", len(df))
        return df
    except Exception as e:
        logger.error("Data generation failed: %s", e)
        return pd.DataFrame()


# ── Vectorized pipeline ────────────────────────────────────────────────────

def _classify_noise_signal(df: pd.DataFrame) -> pd.DataFrame:
    """
    Vectorized noise + signal classification.
    Uses pre-computed _is_noise / _is_discovery flags when available (from generator).
    Falls back to regex on text column for raw data.
    """
    text = df["text"].fillna("").astype(str)

    # If synthetic data, trust the pre-computed flags
    if "_is_noise" in df.columns and "_is_discovery" in df.columns:
        df = df.copy()
        df["_is_noise"] = df["_is_noise"].map(
            lambda v: str(v).lower() in ("true", "1", "yes") if pd.notna(v) else False
        )
        df["_is_discovery"] = df["_is_discovery"].map(
            lambda v: str(v).lower() in ("true", "1", "yes") if pd.notna(v) else False
        )
        # Still detect noise via regex for anything not flagged (belt-and-suspenders)
        regex_noise = text.str.contains(_NOISE_RE.pattern, case=False, regex=True, na=False)
        df["_is_noise"] = df["_is_noise"] | regex_noise
    else:
        df = df.copy()
        df["_is_noise"] = text.str.contains(_NOISE_RE.pattern, case=False, regex=True, na=False)
        df["_is_discovery"] = text.str.contains(_SIGNAL_RE.pattern, case=False, regex=True, na=False)
        # Also keep non-noise reviews with substantial text as "signal" (general reviews)
        long_enough = text.str.len() >= 80
        df["_is_discovery"] = df["_is_discovery"] | (~df["_is_noise"] & long_enough)

    return df


def _infer_tier_vectorized(df: pd.DataFrame) -> pd.Series:
    """Vectorized subscription tier inference."""
    tier = df.get("subscription_tier", pd.Series(dtype=str)).fillna("").astype(str).str.lower()

    # Pre-filled from generator — trust known values
    known = tier.isin(["premium", "free"])
    text = df["text"].fillna("").astype(str)

    premium_match = text.str.contains(PREMIUM_SIGNALS.pattern, case=False, regex=True, na=False)
    free_match = text.str.contains(FREE_SIGNALS.pattern, case=False, regex=True, na=False)

    result = tier.copy()
    result[~known & premium_match] = "premium"
    result[~known & ~premium_match & free_match] = "free"
    result[result == ""] = "unknown"
    return result


def _enrich_row(text: str) -> dict:
    """Per-row enrichment — called only on passed rows (~6,500)."""
    root_causes = [
        name for name, pat in ROOT_CAUSE_RULES.items() if pat.search(text)
    ]
    frustrations = [
        name for name, pat in FRUSTRATION_PATTERNS.items() if pat.search(text)
    ]
    segment_scores = {name: len(pat.findall(text)) for name, pat in SEGMENT_PATTERNS.items()}
    top_segment = max(segment_scores, key=segment_scores.get)
    segment = top_segment if segment_scores[top_segment] > 0 else "General Listener"

    # Pull best verbatim sentence
    sentences = [s.strip() for s in re.split(r"[.!?]\s+", text) if 30 < len(s.strip()) < 280]
    kws = {"echo chamber", "same song", "algorithm", "discover", "loop", "broken", "stale", "repeat", "escape", "feedback"}
    scored = sorted(sentences, key=lambda s: sum(k in s.lower() for k in kws), reverse=True)
    verbatim = scored[0] if scored else text[:200]

    return {
        "root_causes": root_causes or ["General Discovery Frustration"],
        "interaction_frustrations": frustrations or ["Algorithm Quality"],
        "user_segment": segment,
        "verbatim_quote": verbatim,
    }


def run_pipeline(df: pd.DataFrame) -> tuple[list[dict], dict]:
    """
    Full vectorized pipeline.
    Returns (enriched_records_list, stats_dict).
    """
    total = len(df)
    if total == 0:
        return [], {"total_ingested": 0, "total_rejected": 0, "total_used": 0}

    # Step 1 — classify noise/signal (vectorized)
    df = _classify_noise_signal(df)

    # Step 2 — subscription tier (vectorized)
    df["subscription_tier"] = _infer_tier_vectorized(df)

    # Step 3 — split
    noise_df = df[df["_is_noise"]]
    signal_df = df[~df["_is_noise"]].copy()

    n_noise = len(noise_df)
    n_signal = len(signal_df)

    logger.info(
        "Classification: %d total → %d noise (%.1f%%) → %d signal (%.1f%%)",
        total, n_noise, n_noise / total * 100, n_signal, n_signal / total * 100,
    )

    if n_signal == 0:
        return [], {"total_ingested": total, "total_rejected": n_noise, "total_used": 0}

    # Step 4 — vectorized boolean flags on signal rows
    text_col = signal_df["text"].fillna("").astype(str)
    signal_df["is_echo_chamber_mention"] = text_col.str.contains(
        r"echo chamber|feedback loop|same.*recommendation", case=False, regex=True, na=False)
    signal_df["is_discover_weekly_complaint"] = text_col.str.contains(
        r"discover weekly|dw\b", case=False, regex=True, na=False)
    signal_df["is_radio_complaint"] = text_col.str.contains(
        r"radio.*repeat|radio.*same|artist.*radio.*loop", case=False, regex=True, na=False)
    signal_df["is_autoplay_complaint"] = text_col.str.contains(
        r"autoplay.*same|autoplay.*repeat|after.*playlist.*same", case=False, regex=True, na=False)
    signal_df["is_discovery_complaint"] = signal_df["_is_discovery"]

    # Sentiment: prefer pre-computed, derive from text if zero/missing
    sentiment_col = pd.to_numeric(signal_df.get("sentiment_raw", pd.Series(0.0)), errors="coerce").fillna(0.0)
    signal_df["sentiment_score"] = sentiment_col.round(3)

    # Step 5 — per-row enrichment (apply on ~6,500 rows, fast enough)
    enrichment = text_col.apply(_enrich_row)
    signal_df["root_causes"] = enrichment.apply(lambda d: d["root_causes"])
    signal_df["interaction_frustrations"] = enrichment.apply(lambda d: d["interaction_frustrations"])
    signal_df["user_segment"] = enrichment.apply(lambda d: d["user_segment"])
    signal_df["verbatim_quote"] = enrichment.apply(lambda d: d["verbatim_quote"])

    # Override segment with pre-assigned value when the generator supplied one.
    # NLP keyword matching defaults most records to "General Listener"; the generator's
    # weighted distribution produces a realistic segment spread instead.
    if "_user_segment" in signal_df.columns:
        pre_seg = signal_df["_user_segment"].fillna("").astype(str).str.strip()
        valid = pre_seg.str.len() > 0
        signal_df.loc[valid, "user_segment"] = pre_seg[valid]

    # Step 6 — build output records
    out_cols = [
        "id", "source", "subreddit", "category", "author", "title",
        "text", "rating", "score", "created_at", "url",
        "subscription_tier", "sentiment_score",
        "root_causes", "interaction_frustrations", "user_segment", "verbatim_quote",
        "is_echo_chamber_mention", "is_discover_weekly_complaint",
        "is_radio_complaint", "is_autoplay_complaint", "is_discovery_complaint",
    ]
    for col in out_cols:
        if col not in signal_df.columns:
            signal_df[col] = "" if col in ("id", "source", "subreddit", "category", "author", "title", "text", "url", "subscription_tier", "user_segment", "verbatim_quote") else 0

    # Rename body → text if needed
    if "body" in signal_df.columns and "text" not in signal_df.columns:
        signal_df["text"] = signal_df["body"]
    if "created_utc" in signal_df.columns and "created_at" not in signal_df.columns:
        signal_df["created_at"] = signal_df["created_utc"]

    records = signal_df[out_cols].fillna("").to_dict(orient="records")

    # ── Stats ──────────────────────────────────────────────────────────────
    n_used = len(records)
    stats = {
        "total_ingested": total,
        "total_rejected": n_noise,
        "total_used": n_used,
        "rejection_rate": round(n_noise / max(total, 1) * 100, 1),
        "discovery_complaint_rate": round(
            signal_df["is_discovery_complaint"].sum() / max(n_used, 1) * 100, 1),
        "echo_chamber_rate": round(
            signal_df["is_echo_chamber_mention"].sum() / max(n_used, 1) * 100, 1),
        "discover_weekly_dissatisfaction_rate": round(
            signal_df["is_discover_weekly_complaint"].sum() / max(n_used, 1) * 100, 1),
        "radio_repetition_rate": round(
            signal_df["is_radio_complaint"].sum() / max(n_used, 1) * 100, 1),
        "autoplay_saturation_index": round(
            signal_df["is_autoplay_complaint"].sum() / max(n_used, 1) * 100, 1),
        "avg_sentiment": round(float(signal_df["sentiment_score"].mean()), 3),
    }

    logger.info(
        "Pipeline complete: %d ingested → %d rejected → %d used | "
        "discovery_pain=%.1f%% echo=%.1f%% dw=%.1f%%",
        total, n_noise, n_used,
        stats["discovery_complaint_rate"],
        stats["echo_chamber_rate"],
        stats["discover_weekly_dissatisfaction_rate"],
    )

    return records, stats


# ── Persistence ────────────────────────────────────────────────────────────

def save_processed(records: list[dict], stats: dict, data_dir: Path) -> None:
    processed_dir = data_dir / "processed"
    processed_dir.mkdir(parents=True, exist_ok=True)

    with open(processed_dir / "processed_reviews.json", "w", encoding="utf-8") as f:
        json.dump(records, f, ensure_ascii=False)

    with open(processed_dir / "pipeline_stats.json", "w", encoding="utf-8") as f:
        json.dump(stats, f, indent=2)

    logger.info("Saved %d processed records and pipeline stats", len(records))


def run_full_pipeline(data_dir: Path | None = None) -> tuple[list[dict], dict]:
    """End-to-end: load (or generate) → pipeline → save → return."""
    if data_dir is None:
        data_dir = _get_data_dir()

    df = load_or_generate(data_dir)
    if df.empty:
        logger.error("No data available to process")
        return [], {"total_ingested": 0, "total_rejected": 0, "total_used": 0}

    records, stats = run_pipeline(df)
    save_processed(records, stats, data_dir)
    return records, stats


if __name__ == "__main__":
    logging.basicConfig(level=logging.INFO, format="%(levelname)s %(message)s")
    recs, st_ = run_full_pipeline()
    print(f"\nPipeline Results:")
    for k, v in st_.items():
        print(f"  {k}: {v}")
